title: blair's porfolio
name: Blair
email: cher.blair.h@gmail.com
description: >-
  the footsteps of a curious developer


baseurl: ""
url: "https://cherblair.github.io/portfolio.github.io/"


# profile 이미지
profile_image: images/me.jpg


# SNS 아이디
# facebook_id: babycheetah
# instagram_id: babycheetah


# Youtube vid
youtube_vid: #


# Custom Color
primary: 18568e
primary_hover: D3E5F5 #1fa69b
color_1: 2c98f0 
color_2: ec5453
color_3: f9bf3f
color_4: 095e21
color_5: 00132C #062F4F
color_6: FC6472 #2c98f0 
color_7: B8EDCF #ec5453
color_8: EFACA3 #f9bf3f
color_9: C3ECF0 #095e21
color_10: ECCEB2 #2fa499
color_11: A7F2EB #D9D2E9
color_12: D4BA7D #00132C
color_13: 90C9C0 #D9EAD3
color_14: D9D4B6 #2eb3bf
color_15: 24CCB5 #fce5cd
color_16: FAA818 #674ea7 
color_17: 41A30D #b45f06
color_18: FFCE38 #6fa8dc 
color_19: 367D7D #c2d431 
color_20: D33502 #9e296b 
color_21: 6EBCBC #b2c5c4 
color_22: 37526D #f2caca
color_23: ACCECD #6793bd 
color_24: B7AE9D #f1c232
color_25: 8A151B #c6d738


# slider type 0  (텍스트가 우측 정렬된 슬라이더)
slider_0: # 형식에 맞추어 항목 추가
- background_url: images/Matterhorn.jpg
  title: 😎
  subtitle: >- 
    JAVA <br>
    Spring / JPA <br>
    MariaDB / MySQL <br>
    JS / css / html
  position: absolute
  transform: translate( -50%, -50%)
  left: 140px
  bottom: 250px


# slider type 1  (텍스트가 좌측 정렬된 슬라이더)
slider_1: # 형식에 맞추어 항목 추가
- background_url: images/slide_b02.png
  title: Java Web<br>Backend+<br>Developer
  subtitle: >- 
    The footsteps of a<br>
    STEADELY growing developer<br>
  position: absolute
  transform: translate( -50%, -50%)
  left: 140px
  bottom: 0px

# The secret of getting ahead is getting started.
# JAVA <br>
# Spring / JPA <br>
# MariaDB / MySQL <br>
# JS / css / html
# slider type 3  (텍스트가 좌측 정렬된 슬라이더)
slider_2: # 형식에 맞추어 항목 추가
- background_url: images/Matterhorn.jpg
  title: 
  subtitle: >- 
    
    
  position: absolute
  transform: translate( -50%, -50%)
  left: 140px
  bottom: 250px    


# About
about_meta: About Me
about_header: >- 
  "The secret of getting ahead is getting started."
about_introduce: >-
  "전반적인 업무 일선에서 신뢰를 바탕으로 앞장서 나가는 개발자"
about_content: >-
 안녕하세요. <strong>3년차 Java 개발자 김하나(Blair)</strong> 입니다.<br>
 저는 도전과 성취가 있는 삶을 지향합니다. <br>
 항상 배움에 목말라 있고, 사람들과 함께 하는 것을 좋아합니다.<br><br> 
 지난 3년 간 분위기 좋고 능력이 출중한 분들이 모인 작은 회사에서 개발자 커리어의 첫 발을 들여 운이 좋게도 <strong>다양한 포지션</strong>에서 많은 일들을 체득하였습니다. 
 저의 첫 둥지는 <strong>카카오 모빌리티의 자회사</strong>가 되어 더 큰 품에서 다양한 사람들과 협업을 할 수 있었습니다. <br>
 <strong>Java와 Spring, JPA</strong>로 백엔드 실무를 다졌고, <strong>Javascript와 html, css, Ajax, JQuery</strong>를 활용하여 프론드엔드쪽도 작업 해왔습니다. 
 <strong>MySql</strong>에 익숙하고 <strong>Tomcat</strong> 서버 구축도 해보았으며, <strong>flutter</strong>를 사용하여 <strong>안드로이드와 iOS 채팅 앱 출시</strong> 경험도 있습니다. 
 3년 동안 백엔드에서 프론트엔드, 웹에서 앱, 사이트 기획부터 개발 QA, 유지보수 등 전반적인 업무 일선에 있었습니다. <br>
 프로젝트를 도맡아 신뢰를 바탕으로 현장의 소리부터 회사 내부의 이슈들까지 모두 모아 <strong>더 나은 프로그램을 만들어 나가는 데 앞장서 나가는 개발자</strong> 입니다.
about_services: # 형식에 맞추어 항목 추가, css > icomoon.css 파일 참고
- icon: icon-code
  name: Java
- icon: icon-data
  name: Server
- icon: icon-monitor
  name: Web
- icon: icon-phone3
  name: App

about_box_content: 
  The secret of getting ahead is getting started.

about_box_content_color: rgb(255, 255, 255) 

about_box_button:
  link: #
  name: sample


# Tech  skill
tech_meta: TECH SKILLS
tech_header: 저는 현재 이것을 할 수 있습니다.
tech_content: 언어는 Java를 기반으로 하고 있고, 다양한 프레임워크를 활용할 수 있습니다. 
tech_list: # 형식에 맞추어 항목 추가
- name: Java
  color: color-6
  animation: fadeInLeft
  percent: 80
  mark: 80
  content: 자바 언어의 기본적인 문법에 대해 알고 있으며, 자료구조 및 알고리즘을 자바로 공부하였습니다.<br><br>
- name: Spring
  color: color-7
  animation: fadeInRight
  percent: 70
  mark: 70
  content: 스프링 프레임 워크를 활용하여 MVC 패턴으로 다양한 요청을 처리할 수 있습니다. Model, View, Controller, Service 로직을 서비스 전반에 걸쳐 작업해왔습니다. 꾸준히 Spring 프레임워크에 대한 공부를 하고 있습니다. <br><br>
- name: DB
  color: color-8
  animation: fadeInLeft
  percent: 70
  mark: 70
  content: 데이터를 모델링하고 테이블 설계 및 관계성 설정 등을 할 수 있습니다. 실무에서는 MariaDB를 사용하였습니다.<br><br>
- name: JPA
  color: color-9
  animation: fadeInRight
  percent: 70
  mark: 70
  content: 실무에서 반복적인 CRUD SQL을 JPA로 처리하였으며, Join, many To one의 관계 등을 다루어보았습니다.<br> JPA로 처리하지 못하는 복잡한 쿼리의 경우에는 native query를 사용하여 작업 하였습니다.<br><br>
- name: MySQL
  color: color-10
  animation: fadeInLeft
  percent: 60
  mark: 60
  content: 기본적인 CRUD query에 익숙하며 여러 테이블 조인을 통하여 필요한 데이터를 조회할 수 있습니다. <br><br>  
- name: AWS
  color: color-11
  animation: fadeInRight
  percent: 20
  mark: 20
  content: 학과에서 AWS 수업을 수강하였고 간단한 실습도 해보았습니다. 클라우드 서버의 기본적인 이론을 알고 있습니다. <br><br>
- name: HTML
  color: color-12
  animation: fadeInLeft
  percent: 80
  mark: 80
  content: 마크업 언어 문법을 이해하고 화면을 구성할 수 있습니다. 반복적인 부분의 경우 템플릿화 하여 코드의 유지/보수를 용이하게 작업해왔습니다. <br><br>
- name: JavaScript
  color: color-13
  animation: fadeInRight
  percent: 70
  mark: 70
  content: Ajax, JQuery 기타 라이브러리 등을 사용하여 동적인 화면을 구성할 수 있습니다. gitHub의 ExcelJs를 활용하여 스크립트단에서 엑셀 파일을 다운로드 하는 로직을 구현하였고 프로젝트 전반에 적용한 경험이 있습니다. <br><br>
- name: css
  color: color-14
  animation: fadeInLeft
  percent: 50
  mark: 50
  content: 간단한 css 작업을 할 수 있습니다. chrome의 dev tools를 사용하여 css를 예시적으로 적용한 뒤 디자인/프론트엔드 담당과 협의하여 디자인을 수정하곤 했습니다. <br><br>
- name: Flutter
  color: color-15
  animation: fadeInRight
  percent: 70
  mark: 70
  content: flutter를 사용하여 채팅 앱을 만든 후 안드로이드와 iOS에 런칭하였고, 유지/보수 한 경험이 있습니다. <br> 언어는 Dart를 사용하였고, 화면 구성부터 Apatch 서버 구축, 백엔드 로직 개발, 웹서버와의 연동 등 전반적인 작업을 도맡아 진행하였습니다. <br><br>
- name: Android
  color: color-16
  animation: fadeInLeft
  percent: 70
  mark: 70
  content: 안드로이드 & JAVA 앱 교육 과정을 수료하였고, 안드로이드 스튜디오에서 flutter & Dart를 활용하여 앱을 출시한 경험이 있습니다. <br><br>
- name: git
  color: color-17
  animation: fadeInRight
  percent: 70
  mark: 70
  content: git을 사용한 버전 관리에 익숙합니다.<br> 기본적인 명령어를 숙지하고 있으며 여러 프로젝트에서 git을 사용하였습니다. <br><br>
- name: gitLab, gitHub
  color: color-18
  animation: fadeInLeft
  percent: 80
  mark: 80
  content: 학원 프로젝트 및 개인 프로젝트의 경우 gitHub를 사용하고, 회사에서는 gitLab을 사용하였습니다. 둘 다 익숙합니다. <br><br>
- name: jira
  color: color-19
  animation: fadeInRight
  percent: 80
  mark: 80
  content: 프로젝트 일정 관리, 이슈 공유 등의 프로그램으로 jira를 사용하였고, 이슈를 분석하여 필요한 데이터를 뽑아낼 수 있습니다. <br><br>
- name: notion
  color: color-20
  animation: fadeInLeft
  percent: 80
  mark: 80
  content: 회사의 공유 자료를 notion으로 만들어 직원들에게 공유한 적이 있으며, notion을 일상에서도 활용하고 있습니다. <br><br>
- name: slack
  color: color-21
  animation: fadeInRight
  percent: 80
  mark: 80
  content: 업무 협업 툴로 slack을 사용하여 익숙합니다. <br><br>



  
tech_desc: 강점은 더 강화하고 부족한 부분은 채우기 위해 직접 부딪혀보며 성장하고 있습니다. <strong>JAVA, Spring, JPA, AWS, docker, React, nodeJS, algorithm</strong>등을 계속해서 조금씩 공부할 생각입니다. 


# Project
project_meta: My Work
project_header: PROJECT
# project_introduce: <span></span>
project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다:)    # 더보기 내용
project_load_more_url: #

project_my_name: COMPANY PROJECT

project_my: # 형식에 맞추어 항목 추가
- background_url: images/pr_rs.png
  animation: fadeInLeft
  name: RS 이기종 통합 주차관제 솔루션
  description: 각기 다른 주차 장비를 연동하여 통합 제어 할 수 있는 프로그램 솔루션의 개발 및 유지 보수 <br> 2020.07 ~ 2023.05
  # detail_url: #
  readmore_url: 

- background_url: images/pr_illo.png
  animation: fadeInLeft
  name: 아파트 방문예약 앱
  description: 아파트 방문예약 앱 기획 및 데이터 모델링 <br> 2022.02 ~ 2022.04 
  # detail_url: #
  readmore_url: #

- background_url: images/pr_chat.png
  animation: fadeInLeft
  name: SaidaTalk
  description: flutter로 Android와 iOS 채팅앱 기획 및 개발, 유지 보수 <br> 2021.08 ~ 2022.08
  # detail_url: #
  readmore_url: 

- background_url: images/pr_hahapet.png
  animation: fadeInLeft
  name: HAHAPET
  description: 반려동물 용품 판매 사이트 기획 및 개발, 유지 보수 <br> 2020.10 ~ 2022.08
  # detail_url: #
  readmore_url:

- background_url: images/pr_cb01.png
  animation: fadeInLeft
  name: C-bridge SAIDA
  description: K-CULTURE 글로벌 소통 플랫폼. <br> 추가 기능 개발 및 사이트 유지 보수 <br> 2020.10 ~ 2022.08
  # detail_url: #
  readmore_url: 

- background_url: images/pr_live.png
  animation: fadeInLeft
  name: c-bridge SAIDA On-live
  description: 생방송 실시간 송출 서비스. <br> 라이브 스트리밍 구현 보조, 기능 추가 및 유지 보수 <br> 2020.07 ~ 2020.12 
  # detail_url: #
  readmore_url: 
 

project_team_name: ACADEMY PROJECT
project_team: # 형식에 맞추어 항목 추가
- background_url: images/pr_pms.png
  animation: fadeInRight
  name: PMS system
  description: 팀원들과 함께 Spring 프레임워크를 활용하여 MVC 패턴에 기반한 PMS system 구축 <br> 2020.05 ~ 2020.06
  detail_url: #
  readmore_url: http://www.daum.net

- background_url: images/pr_kid.png
  animation: fadeInRight
  name: 어린이 체험 학습 사이트
  description: html, javascript, css, Oracle DB를 사용한 동적 화면 구현 <br> 2020.04
  detail_url: #
  # readmore_url: #

# project_business_name: Business
# project_business: # 형식에 맞추어 항목 추가
# - background_url: images/my_business.PNG
#   animation: fadeInTop
#   name: 인프런강의(2021~)
#   description: >-
#     취준과 대학원진학을 동시에 했을때 많은 곳에서 github 주소뿐만아니라 개발 블로그주소도 요청하는데가 많았다.(물론 필수는 아니였지만) 
#     또한 교육기관(멋쟁이사자처럼,네이버 부스트 캠프, 소마등)에서도 마찬가지이다. 현재 프로그래밍의 중요도가 올라가고있으며 초등학생부터 의무교육을 시작한다고 한다. 
#     많은 비전공자들이 뒤늦게 프로그래밍을 시작하고 있다. 열심히 배우고 지원할려니 개발 블로그를 요청한다... 프로그래밍을 시작할때 알았다면 얼마나 좋았을까. 
#     공부하면서 블로그 내용을 채웠으면 참 좋았을것이다. 이런 흐름을 캐치하여 나는 개발자다운 블로그인 깃헙블로그를 만드는 짧은 강의를 만들었다. 
#   detail_url: #
#   readmore_url: #


# Experience
exp_meta: What have I achieved?
exp_header: 저는 이런 "경험"들을 해봤습니다.
exp_content: 현재 개발로서는 큰 도움은 되지 않을 수 있지만, 회사에서 필요로 한다면 이런 역량도 가지고 있습니다.
exp_services: # 형식에 맞추어 항목 추가
- name: 매니지먼트
  color: color-1
  icon: icon-bulb
  # content: 6개의 프로젝트 모두 팀장을 맡아 각 팀원들의 능력을 파악하고 업무를 배정하고 관리하였습니다.
- name: 기술습득
  color: color-2
  icon: icon-home
  # content: 제가 선택한 길, 항상 열정을 다해 공부하며 새로운 기술에 대해 즐거운 마음으로 배웁니다.
- name: 프로젝트
  color: color-3
  icon: icon-phone3
  # content: 다양한 프로젝트를 기획, 진행 해왔기에 업무에 대한 협력과 배분이 익숙합니다. 새로운 프로젝트에 도전적입니다.

exp_counters_bg_img: images/img_bg_4.jpg
exp_counters:
# - name: Online Class Sales
#   count: 344
#   speed: 10000
- name: project
  count: 8
  speed: 100


# Career
carerr_meta: career
career_header: Work Career
career_list:
- name: RS SOLUTIONS
  date: 2020.07 ~ 2023.05
  content: 이기종 주차 시스템 연동 프로젝트 및 다양한 SI 프로젝트 수행
  color: color-1
  icon: icon-pen2
  animation: fadeInLeft
- name: EZEN ACADEMY
  date: 2019.12 ~ 2020.06
  content: JAVA, ANDROID 웹 & 앱 개발자 과정 수료
  color: color-3
  icon: icon-pen2
  animation: fadeInRight


# Education
edu_meta: Education
edu_header: Education
edu_list:
# - title: KOREA UNIVERSITY ARTIFICIAL INTELLIGENCE MASTER'S DEGREE
#   subtitle: 고려대 인공지능학과 대학원 석사과정
#   date: 20xx.01 - 현재
#   content: 설명설명 설명글 
# - title: HANSUNG UNIVERSITY
#   subtitle: xx대학교 xx과 졸업
#   date: 20xx.03 - 20xx.02
#   content: 나에대한 간단한 설명글 
# - title: YEOUIDO HIGH SCHOOL
#   subtitle: xx고등학교
#   date: 20xx.03 - 20xx.02
#   content: >-
#     설명글
#     설명글
#     설명글
#     설명글


# Blog
blog_meta: self-improvement
blog_header: BLOG AND GITHUB
blog_load_more: 더 발전하기 위해 항상 노력합니다    # 더보기 내용
# blog_load_more_url: #
blog_list:
# - title: 
#   subtitle: 개발 블로그 운영
#   date: 2021.01
#   content: 여러 분야의 프로그래머들을 보면서 부러워도 하고 좌절도 하였지만 포기하지않고 어느 한분야라도 '장인'이 되겠다는 마음으로 꾸준히 개발 블로그를 운영해오고 있습니다.
#   thumbnail_url: images/blog-1.PNG
#   link: #
# - title: 따라쟁이의 유튜브
#   subtitle: 개발,논문 유튜브 채널 운영
#   date: 2018.04
#   content: 유튜브 채널을 운영하며 배운 것들을 정리해서 영상을 촬영하고 있습니다. 개인적으로 복습을 한번 더 하는 장점이 있습니다.
#   thumbnail_url: images/blog-2.PNG
#   link: #
# - title: 네이버블로그
#   subtitle: 이전 블로그
#   date: 2018.03
#   content: 막 복학을하고 전과했을때 시작했던 첫블로그입니다.
#   thumbnail_url: images/blog-3.PNG
#   link: #


# Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
- title: cher.blair.h@gmail.com
  icon: icon-globe-outline
# - title: 대한민국
#   icon: icon-map
- title: +82 10 9810 1101
  icon: icon-phone
# - title: 웹 주소
#   icon: icon-layers2
#   url: https://google.com
contact_message: <em>연락해주셔서 감사합니다.</em> 24시간이내에 회신드리도록 하겠습니다.


optional_front_matter:
  remove_originals:    true
